/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectPanel.java
 *
 * Created on 2010年10月21日, 上午09:08:28
 */
package com.xu81.lgtools.avg.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author xu81
 */
public class ProjectPanel extends javax.swing.JPanel {

    /** Creates new form ProjectPanel */
    public ProjectPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProjName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProjPath = new javax.swing.JTextField();
        btnSelProjPath = new javax.swing.JButton();
        cbCreatePath = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        cbAutoCreatePath = new javax.swing.JCheckBox();
        cbCustomPath = new javax.swing.JCheckBox();
        txtCreatePath = new javax.swing.JTextField();
        btnSelCreatePath = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProjDesc = new javax.swing.JTextPane();

        jLabel1.setText("项目名称:");

        jLabel2.setText("项目路径:");

        btnSelProjPath.setText("浏览");
        btnSelProjPath.setName("btnProjPath"); // NOI18N
        btnSelProjPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPath(evt);
            }
        });

        cbCreatePath.setSelected(true);
        cbCreatePath.setText("创建资源文件夹");
        cbCreatePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCreatePathActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbAutoCreatePath.setSelected(true);
        cbAutoCreatePath.setText("自动创建");
        cbAutoCreatePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAutoCreatePathActionPerformed(evt);
            }
        });

        cbCustomPath.setText("自定义:");
        cbCustomPath.setEnabled(false);
        cbCustomPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCustomPathActionPerformed(evt);
            }
        });

        txtCreatePath.setEnabled(false);

        btnSelCreatePath.setText("浏览");
        btnSelCreatePath.setEnabled(false);
        btnSelCreatePath.setName("btnCustomPath"); // NOI18N
        btnSelCreatePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPath(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAutoCreatePath)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbCustomPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreatePath, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelCreatePath)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAutoCreatePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCustomPath)
                    .addComponent(txtCreatePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelCreatePath))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtProjDesc.setEditable(false);
        jScrollPane1.setViewportView(txtProjDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProjPath, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelProjPath))
                    .addComponent(cbCreatePath))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProjName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProjPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelProjPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCreatePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCreatePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCreatePathActionPerformed
        // TODO add your handling code here:
        boolean isSelected = cbCreatePath.isSelected();
        cbAutoCreatePath.setEnabled(isSelected);
        cbCustomPath.setEnabled(false);
        txtCreatePath.setEnabled(false);
        btnSelCreatePath.setEnabled(false);
    }//GEN-LAST:event_cbCreatePathActionPerformed

    private void cbAutoCreatePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAutoCreatePathActionPerformed
        // TODO add your handling code here:
        boolean isSelected = cbAutoCreatePath.isSelected();
        cbCustomPath.setEnabled(!isSelected);
    }//GEN-LAST:event_cbAutoCreatePathActionPerformed

    private void cbCustomPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCustomPathActionPerformed
        // TODO add your handling code here:
        txtCreatePath.setEnabled(cbCustomPath.isEnabled() && cbCustomPath.isSelected());
        btnSelCreatePath.setEnabled(cbCustomPath.isEnabled() && cbCustomPath.isSelected());
    }//GEN-LAST:event_cbCustomPathActionPerformed

    private void selectPath(java.awt.event.ActionEvent evt) {
        String btnName = ((JButton)evt.getSource()).getName();
        jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jfc.showDialog(this, "选择");
        if (result == 0) {
            if("btnProjPath".equals(btnName)){
                txtProjPath.setText(jfc.getSelectedFile().getAbsolutePath());
            }else if("btnCustomPath".equals(btnName)){
                txtCreatePath.setText(jfc.getSelectedFile().getAbsolutePath());
            }
        }
    }

    public JCheckBox getCbAutoCreatePath() {
        return cbAutoCreatePath;
    }

    public void setCbAutoCreatePath(JCheckBox cbAutoCreatePath) {
        this.cbAutoCreatePath = cbAutoCreatePath;
    }

    public JCheckBox getCbCreatePath() {
        return cbCreatePath;
    }

    public void setCbCreatePath(JCheckBox cbCreatePath) {
        this.cbCreatePath = cbCreatePath;
    }

    public JCheckBox getCbCustomPath() {
        return cbCustomPath;
    }

    public void setCbCustomPath(JCheckBox cbCustomPath) {
        this.cbCustomPath = cbCustomPath;
    }

    public JTextField getTxtCreatePath() {
        return txtCreatePath;
    }

    public void setTxtCreatePath(JTextField txtCreatePath) {
        this.txtCreatePath = txtCreatePath;
    }

    public JTextField getTxtProjName() {
        return txtProjName;
    }

    public void setTxtProjName(JTextField txtProjName) {
        this.txtProjName = txtProjName;
    }

    public JTextField getTxtProjPath() {
        return txtProjPath;
    }

    public void setTxtProjPath(JTextField txtProjPath) {
        this.txtProjPath = txtProjPath;
    }

    public String finish() {
        return "";
    }
    private JFileChooser jfc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelCreatePath;
    private javax.swing.JButton btnSelProjPath;
    private javax.swing.JCheckBox cbAutoCreatePath;
    private javax.swing.JCheckBox cbCreatePath;
    private javax.swing.JCheckBox cbCustomPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCreatePath;
    private javax.swing.JTextPane txtProjDesc;
    private javax.swing.JTextField txtProjName;
    private javax.swing.JTextField txtProjPath;
    // End of variables declaration//GEN-END:variables
}
